# Generated by Django 4.1.5 on 2023-02-01 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invista_me", "0002_investimento_nivel"),
    ]

    operations = [
        migrations.RemoveField(model_name="investimento", name="nivel",),
    ]
